apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certs
subjects:
- kind: ServiceAccount
  name: certs
roleRef:
  kind: Role
  name: certs
  apiGroup: rbac.authorization.k8s.io