apiVersion: v1
entries:
  certs:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-06-06T20:54:17.972594+02:00
    description: A Helm chart for managing Let's encrypt certificates
    digest: 790b6902ad4b95bcfd6f6906d2f028d7fd723e8fecb4c5774b9b6c565b104aae
    name: certs
    urls:
    - https://math-nao.github.io/certs/charts/certs-1.0.0.tgz
    version: 1.0.0
generated: 2019-06-06T20:54:17.97134+02:00
